substitutions:
  run_uom: s
  run_duration_initial_value: '5'
  rain_sensor_id: rain_sensor
  rtc_id: rtc_time
  timezone: CST
  day_update_interval: 3min
  hourly_update_interval: 60min
  default_update_interval: 30s
  # Controller setup
  cntrlr_id: sprinkler_cntrlr
  cntrlr_name: "Sprinkler Controller"
  z1_name: "Zone 1"
  z2_name: "Zone 2"
  z3_name: "Zone 3"
  z4_name: "Zone 4"
  z5_name: "Zone 5"
  z6_name: "Zone 6"
  z7_name: "Zone 7"
  z8_name: "Zone 8"
  led_ready:
    id: rgb_led
    brightness: 100%
    # Green
    red: 0%
    green: 80%
    blue: 0%
    effect: none

  led_running:
    id: rgb_led
    brightness: 100%
    # Purple 
    red: 95%
    green: 2%
    blue: 100%
    effect: none

  led_standby:
    id: rgb_led
    brightness: 100%
    # Orange 
    red: 97%
    green: 46%
    blue: 19%
    effect: none
  
  led_pause:
    id: rgb_led
    brightness: 100%
    # Purple 
    red: 95%
    green: 2%
    blue: 100%
    effect: Pulse

esphome:
  name: waveshare-esprinkler
  comment: "WaveShare ESP32-S3-POE-ETH-8DI-8RO device"
  friendly_name: "Waveshare Esprinkler"
  name_add_mac_suffix: false
  on_boot:
    then:
      - pcf85063.read_time
      - rtttl.play:
          rtttl: scale_up:d=32,o=5,b=150:c,e,8g
      - light.turn_on: ${led_ready}
          # id: rgb_led
          
          # brightness: 100%
          # red: 95%
          # green: 2%
          # blue: 100%

esp32:
  board: esp32s3box #esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

psram:
  mode: octal
  speed: 80MHz

web_server:
  version: 3

# Enable logging
logger:
  level: INFO

# debug:
#   update_interval: 5s


packages:
  # Time, IP, MAC addr, Wifi info, Temperature, etc
  # - !include hardware/waveshare-8DI-8RO-C.yaml
  # - !include sensors/generic_sensors.yaml
  # - !include controller/controller.yaml
  # - !include controller/controller_status.yaml
  # - !include schedule/schedule.yaml
  # - !include schedule/zone_duration.yaml
  
  ##### Uncomment below if compiling from esphome builder #####
  - !include esprinkler/common/network_setup.yaml
  - !include esprinkler/hardware/waveshare-8DI-8RO-C.yaml
  - !include esprinkler/sensors/generic_sensors.yaml
  - !include esprinkler/controller/controller.yaml
  - !include esprinkler/controller/controller_status.yaml
  - !include esprinkler/schedule/schedule.yaml
  - !include esprinkler/schedule/zone_duration.yaml


